### ISSUE TITLE
has been compiled by a more recent version of the Java Runtime class file version 55.0 - error

### ISSUE THREAD

**Issue by exchangeadmin666** [idealo/mongodb-performance-test#16]
F1.

error is:
>java -jar mongodb-performance-test.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: ch/qos/logback/classic/spi/LogbackServiceProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

i have:
windows 11
>java -showversion
java version "1.8.0_411"
Java(TM) SE Runtime Environment (build 1.8.0_411-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.411-b09, mixed mode)

**Comment by kagahd** [comment]
The error message indicates that the program you're trying to run was compiled with a newer version of the Java Development Kit (JDK) than the one you currently have installed. Specifically, the class LogbackServiceProvider was compiled with a class file version 55.0, but your current Java version only supports class file versions up to 52.0.

Here are the corresponding Java versions and their class file versions:

Java 8: Class file version 52.0
Java 9: Class file version 53.0
Java 10: Class file version 54.0
Java 11: Class file version 55.0
Java 12: Class file version 56.0
etc.
Your current Java version is 1.8 (Java 8), which only supports class file versions up to 52.0. The program, however, requires at least Java 11, which supports class file versions up to 55.0.

To solve this problem, you need to install a newer version of Java.
