### ISSUE TITLE
Run test with SSL connection

### ISSUE THREAD

**Issue by hartman17** [idealo/mongodb-performance-test#2]
Are you able to use this tool with SSL connections to the database?   I've tried -ssl TRUE  and -ssl with no luck

**Comment by kagahd** [comment]
SSL is not supported. While it's not complicate to do so I wonder why you would need it. This tool is just for measuring performance, to be able to compare the performance of one server with another or one mongodb version with another. Why would you encrypt the communication channel for doing this?

**Comment by kagahd** [comment]
SSL support has been added in v1.1.0.
